#!/usr/bin/env python3
"""Generate a post-flight Markdown report from an FDR session.

Usage:
    post-flight-report.py <fdr_base_path> [--out <report.md>]

Where <fdr_base_path> is the path prefix without extension — the same value
passed to FlightDataRecorder::open() on the C++ side. The script reads:
    <base>.m130session.json   — session manifest (counts, SHA-256 per track)
    <base>.m130events         — JSON-lines event log
    <base>.m130structured     — JSON-lines decoded telemetry samples

The report is intentionally Markdown-only. PDF rendering is handled by the
compliance pipeline (Sphinx / pandoc) which consumes this file. Keeping the
generator stdlib-only means it can run in any CI environment without extra
dependencies (REQ-M130-GCS-LOG-005).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any


def _load_manifest(path: str) -> dict[str, Any]:
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _load_jsonl(path: str, limit: int | None = None) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    if not os.path.exists(path):
        return out
    with open(path, encoding="utf-8") as fh:
        for i, line in enumerate(fh):
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
            if limit is not None and len(out) >= limit:
                break
    return out


def _alert_summary(events: list[dict[str, Any]]) -> dict[str, int]:
    by_level: dict[str, int] = {}
    for e in events:
        lvl = str(e.get("level", "info"))
        by_level[lvl] = by_level.get(lvl, 0) + 1
    return by_level


def _structured_summary(samples: list[dict[str, Any]]) -> dict[str, dict[str, float]]:
    """Per-field min/max/last across the structured samples."""
    stats: dict[str, dict[str, float]] = {}
    for s in samples:
        for k, v in (s.get("n") or {}).items():
            if not isinstance(v, (int, float)):
                continue
            row = stats.setdefault(k, {"min": float("inf"), "max": float("-inf"), "last": 0.0})
            row["min"] = min(row["min"], float(v))
            row["max"] = max(row["max"], float(v))
            row["last"] = float(v)
    return stats


def _fmt_us(ts_us: int) -> str:
    s = ts_us / 1_000_000.0
    return f"{s:.6f} s"


def build_report(base: str) -> str:
    manifest = _load_manifest(base + ".m130session.json")
    events     = _load_jsonl(base + ".m130events")
    structured = _load_jsonl(base + ".m130structured")

    out: list[str] = []
    w = out.append
    w("# M130 Post-Flight Report")
    w("")
    w("> Auto-generated by `tools/post-flight-report.py`. Do not edit by hand.")
    w("")
    w("## Session")
    w("")
    w(f"- schema_version: `{manifest.get('schema_version', '?')}`")
    w(f"- session_start_us: `{manifest.get('session_start_us', 0)}` ({_fmt_us(int(manifest.get('session_start_us', 0)))})")
    w(f"- session_end_us:   `{manifest.get('session_end_us', 0)}` ({_fmt_us(int(manifest.get('session_end_us', 0)))})")
    w(f"- bytes_written:    `{manifest.get('bytes_written', 0)}`")
    counts = manifest.get("counts", {})
    w(f"- counts: raw=`{counts.get('raw', 0)}`, events=`{counts.get('events', 0)}`, structured=`{counts.get('structured', 0)}`")
    w("")

    w("## Track integrity (SHA-256)")
    w("")
    w("| Track | Path | Size (bytes) | SHA-256 |")
    w("|---|---|---:|---|")
    for tk in ("raw", "events", "structured"):
        t = manifest.get("tracks", {}).get(tk, {})
        w(f"| {tk} | `{t.get('path', '')}` | {t.get('size', 0)} | `{t.get('sha256', '')}` |")
    w("")

    if events:
        w("## Alerts & events")
        w("")
        w("| Level | Count |")
        w("|---|---:|")
        for lvl, n in sorted(_alert_summary(events).items()):
            w(f"| {lvl} | {n} |")
        w("")
        w("### Last 10 events")
        w("")
        w("| ts_ms | level | source | message |")
        w("|---|---|---|---|")
        for e in events[-10:]:
            msg = str(e.get("message", "")).replace("|", "\\|")
            w(f"| {e.get('ts', 0)} | {e.get('level', '')} | {e.get('source', '')} | {msg} |")
        w("")

    if structured:
        w("## GNC field statistics")
        w("")
        w("| Field | Min | Max | Last |")
        w("|---|---:|---:|---:|")
        for k, stats in sorted(_structured_summary(structured).items()):
            w(f"| {k} | {stats['min']:.6g} | {stats['max']:.6g} | {stats['last']:.6g} |")
        w("")

    w("---")
    w("")
    w("Generated by `tools/post-flight-report.py`.")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("base", help="FDR base path (no extension)")
    ap.add_argument("--out", default=None, help="Output Markdown path (default: <base>.report.md)")
    args = ap.parse_args(argv)

    base = args.base
    manifest_path = base + ".m130session.json"
    if not os.path.exists(manifest_path):
        print(f"error: manifest not found at {manifest_path}", file=sys.stderr)
        return 2

    report = build_report(base)
    out_path = args.out or (base + ".report.md")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(report)
    print(out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
